# Generated by Django 3.0.6 on 2020-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=250)),
                ('receiver', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=5000)),
                ('subject', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='creation_date')),
                ('inbox_mode', models.CharField(default='inbox', max_length=100)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
